routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\CoursesController;
use App\Http\Controllers\Admin\LessonsController;
use App\Http\Controllers\Admin\StudentsController;
use App\Http\Controllers\Admin\CommentsController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\OrdersController;

use App\Http\Controllers\HomeController as HomeControllerAlias;
use App\Http\Controllers\Web\CoursesController as CoursesControllerAlias;
use App\Http\Controllers\Web\OrdersController as OrdersControllerAlias;
use App\Http\Controllers\Web\UsersController as UsersControllerAlias;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\CategoriesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeControllerAlias::class, 'index'])->name('home');
Route::get('/mailview', function (){
    $order = \App\Models\Orders::first();
    return view('mail.buy-notification', compact('order'));
});

/*
 * Course section
 */
Route::get('/course/{slug}', [CoursesControllerAlias::class, 'course'])->name('course.show');
Route::get('/course/{course}/lesson/{lesson}', [CoursesControllerAlias::class, 'lesson'])->name('course.lesson')->middleware('auth');
Route::get('/lesson/{lesson}/finish', [CoursesControllerAlias::class, 'lessonFinish'])->name('course.lesson.finish')->middleware('auth');;
Route::get('/course/curso-diego/module/1/evaluation', function (){
    $eval  = \App\Models\Evaluations::first();
    return view('front.evaluation', compact('eval'));
})->name('course.module.evaluation')->middleware('auth');;


/*
 * Profile section
 */
Route::get('/profile', [UsersControllerAlias::class, 'index'])->name('profile');
Route::post('/profile/{id}/update', [UsersControllerAlias::class, 'update'])->name('profile.update');

/*
 * Payment section
 */
Route::get('/checkout/{course}', [OrdersControllerAlias::class, 'checkout'])->name('order.checkout')->middleware('auth');
Route::get('/checkout/{course}/finish', [OrdersControllerAlias::class, 'finish'])->name('order.checkout.finish');
Route::get('/payment/insert/{course}', [OrdersControllerAlias::class, 'insertPayment'])->name('order.payment.insert');
Route::post('/payment/confirm', [OrdersControllerAlias::class, 'confirmPayment'])->name('order.payment.confirm');
Route::get('/payment/rollback/{order}', [OrdersControllerAlias::class, 'rollbackPayment'])->name('order.payment.rollback');
Route::get('/payment/get/{order}', [OrdersControllerAlias::class, 'getPayment'])->name('order.payment.get');

Route::get('/payment/test', function (){
    $order = \App\Models\Orders::first();
    $course = $order->course;
    return view('front.store.finish', compact('order', 'course'));
})->name('order.payment.get');



Route::get('/miscursos', function(){
    return view('front.profile.miscursos');
});


//Route::middleware(['auth:sanctum', 'verified'])->group()->get('/dashboard', function () {
//    return view('dashboard');
//})->name('dashboard');


Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'middleware' => 'auth:sanctum'
    //'middleware' => ['auth:sanctum', 'role:admin']
], function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('categories', CategoriesController::class);
    Route::resource('courses', CoursesController::class);
    Route::resource('students', StudentsController::class);
    Route::resource('lessons', LessonsController::class);
    Route::resource('comments', CommentsController::class);
    Route::resource('users', UsersController::class);
    Route::resource('orders', OrdersController::class);

    //Route::resource('courses', )
});

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    //Route::resource('categories', CategoriesController::class);
});

app/Models/Orders.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Orders extends Model
{
    use HasFactory;

    protected $fillable = [
        'amount',
        'paid',
        'course_id',
        'user_id',
        'payment_method_id',
        'voucher',
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function course()
    {
        return $this->belongsTo(Courses::class, 'course_id');
    }

    public function payment_method()
    {
        return $this->belongsTo(PaymentMethods::class, 'payment_method_id');
    }
}

app/Http/Controllers/Admin/OrdersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Orders;
use Illuminate\Http\Request;

class OrdersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Orders::paginate('12');
        return view('administration.orders.index', compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Web/OrdersController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use App\Mail\BuyNotification;
use App\Models\Courses;
use App\Models\Orders;
use App\Services\BancardService;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class OrdersController extends Controller
{
    public function checkout($course)
    {
        $course = Courses::where('slug', $course)->first();

        if (\Auth::user()->orders->where('course_id', $course->id)->first()) {
            return redirect()->route('home')->with('error', 'Ya has comprado este curso');
        }

        return view('front.store.checkout', compact('course'));
    }

    public function insertPayment(Courses $course)
    {
        try {
            \DB::beginTransaction();
            $order = new Orders();
            $order->amount      = $course->price;
            $order->paid        = false;
            $order->course_id   = $course->id;
            $order->user_id     = \Auth::id();
            $order->payment_method_id     = 1;
            $order->save();
            \Log::debug('OrdersController@insertPayment - Order ID: '.$order->id);

            $bancard = new BancardService();
            $result = $bancard->singleBuy($order);

            \DB::commit();

            if ($result->status == 'success') {

                \Log::debug('OrdersController@insertPayment - bancard->status = success');
                return view('front.store.bancard_form', compact('result'));
            }else{
                \Log::debug('OrdersController@insertPayment - bancard->status = fail');
                return redirect()->route('order.checkout', $course->slug)->with('error', 'No se pudo procesar la orden de pago');
            }

        }catch (\Exception $e){
            dd($e->getMessage());
            \DB::rollBack();
        }
    }

    public function confirmPayment(Request $request)
    {
        try {
            if ($order = Orders::find($request->operation['shop_process_id'])) {
                \Log::debug('OrdersController@confirmPayment - Order ID: '.$order->id);
                $order->payment = $request->operation;
                if ($request->operation['response_code'] == '00') {
                    $order->paid = true;
                }else {
                    $order->paid = false;
                }
                $order->save();

                return response()->json(['success' => true]);
            }

            return response()->json(['success' => false]);

        } catch (\Exception $e) {
            \Log::error('OrdersController@confirmPayment - Line: '.$e->getLine() .' Message: '.$e->getMessage());

            return response()->json(['success' => false]);
        }
    }

    public function finish($order)
    {
        $order = Orders::find($order);
        \Log::debug('OrdersController@finish - order: '.json_encode($order));
        try {
            if ($order->payment_method_id == 1) {

                if ($order->paid) {
                    //\Mail::to($order->user->email)->send(new BuyNotification($order));
                    return view('front.store.finish', compact('order'));
                }else {
                    return redirect()->route('order.checkout', $order->course->slug)
                        ->with('bancard_response', json_encode([
                            'response_description' => json_decode($order->payment)['response_description'],
                            'extended_response_description' => json_decode($order->payment)['extended_response_description'],
                        ]));
                }
            }else {
                return view('front.store.finish', compact('order'));
            }
        }catch (\Exception $e){
            //dd('11');

            \Log::error('OrdersController@finish - Line: '.$e->getLine() .' Message: '.$e->getMessage());

            return redirect()->route('order.checkout', $order->course->slug)->with('error', 'No se pudo procesar el pago');
        }
    }

    public function rollbackPayment(Orders $order)
    {
        $bancard = new BancardService();
        $bancard->rollbackPayment($order);
    }

    public function getPayment(Orders $order)
    {
        $bancard = new BancardService();


        return $bancard->getPayment($order);
    }
}

app/Http/Livewire/Admin/Orders/Index.php
<?php

namespace App\Http\Livewire\Admin\Orders;

use App\Models\Orders;
use Livewire\Component;
use Livewire\WithPagination;

class Index extends Component
{
    use WithPagination;

    protected $paginationTheme = 'bootstrap';
    public $search = '';

    public function paid(Orders $order)
    {
        $order->paid = !$order->paid;
        $order->save();
    }

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function render()
    {
        return view('livewire.admin.orders.index', [
            /*'orders' => Orders::orderBy('created_at', 'DESC')->paginate(5),*/
            'orders' => Orders::whereHas('user', function ($r) {
                $r->where('name', 'like', '%'.$this->search.'%')
                    ->orWhere('email', 'like', '%'.$this->search.'%');
            })->orderBy('created_at', 'DESC')->paginate(5),
        ]);
        //return view('livewire.admin.orders.index');
    }
}

resources/views/livewire/admin/orders/index.blade.php
<div>
    <div class="card-body">
        <h4 class="card-title">
            <i class="fas fa-newspaper"></i>
            Ordenes
            {{--<a href="{{ route('admin.categories.create') }}" class="fa-pull-right btn btn-info btn-xs"><i class="fas fa-plus"></i></a>--}}
        </h4>
        <div class="row">
            <div class="col-sm-12 col-md-6">

            </div>
            <div class="col-sm-12 col-md-6">
                <div id="order-listing_filter" class="dataTables_filter">
                    <label>
                        <input type="search"
                               wire:model="search"
                               class="form-control"
                               placeholder="Buscar"
                               aria-controls="order-listing">
                    </label>
                </div>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Curso</th>
                    <th>Alumno</th>
                    <th>Método Pago</th>
                    <th>Transacción</th>
                    <th>Pagado</th>
                    <th>Fecha</th>
                    <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($orders as $order)
                    <tr>
                        <td class="font-weight-bold">
                            {{ $order->id }}
                        </td>
                        <td class="text-muted">
                            {{ $order->course->title }}
                        </td>
                        <td class="text-muted">
                            {{ $order->user->name }}
                        </td>
                        <td class="text-muted">
                            {{ $order->payment_method->description ?? '' }}
                        </td>
                        <td class="text-muted">
                            @if ($order->payment && $order->payment_method_id == 1)
                                <table>
                                    <tr>
                                        <th>Estado</th>
                                        <td>{{ json_decode($order->payment)->response_description }}</td>
                                    </tr>
                                    <tr>
                                        <th>Ticket</th>
                                        <td>{{ json_decode($order->payment)->ticket_number }}</td>
                                    </tr>
                                    <tr>
                                        <th>Monto</th>
                                        <td>{{ number_format(json_decode($order->payment)->amount) }}</td>
                                    </tr>
                                </table>
                            @elseif ($order->payment_method_id == 2)
                                Comprobante Nro.
                                <br>
                                {{ $order->voucher }}
                            @endif
                        </td>
                        <td class="text-muted">
                            <label class="badge badge-{{ $order->paid ? 'success' : 'danger' }} badge-pill">{{ $order->paid ? 'SI' : 'NO' }}</label>
                        </td>
                        <td class="text-muted">
                            {{ $order->created_at }}
                        </td>
                        <td>
                            @if ($order->payment_method_id == 2)
                                @if (!$order->paid)
                                    <button class="btn btn-info btn-xs" wire:click="paid({{ $order->id }})">Aprobar</button>
                                @else
                                    <button class="btn btn-warning btn-xs" wire:click="paid({{ $order->id }})">Deshacer</button>
                                @endif
                            @endif
                        </td>
                        {{--<td>
                            {!! Form::open(['route' => ['admin.categories.destroy', $category->id], 'method' => 'DELETE']) !!}
                                <button type="submit" class="btn btn-outline-danger btn-xs"><i class="fas fa-trash"></i></button>
                            {!! Form::close() !!}
                            <a href="{{ route('admin.categories.edit', $category->id) }}" class="btn btn-outline-info btn-xs"><i class="fas fa-pencil-alt"></i></a>
                        </td>--}}
                    </tr>
                @endforeach
                </tbody>
            </table>
            {{ $orders->links() }}
        </div>
    </div>
</div>