routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\CoursesController;
use App\Http\Controllers\Admin\LessonsController;
use App\Http\Controllers\Admin\StudentsController;
use App\Http\Controllers\Admin\CommentsController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\OrdersController;

use App\Http\Controllers\HomeController as HomeControllerAlias;
use App\Http\Controllers\Web\CoursesController as CoursesControllerAlias;
use App\Http\Controllers\Web\OrdersController as OrdersControllerAlias;
use App\Http\Controllers\Web\UsersController as UsersControllerAlias;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\CategoriesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeControllerAlias::class, 'index'])->name('home');
Route::get('/mailview', function (){
    $order = \App\Models\Orders::first();
    return view('mail.buy-notification', compact('order'));
});

/*
 * Course section
 */
Route::get('/course/{slug}', [CoursesControllerAlias::class, 'course'])->name('course.show');
Route::get('/course/{course}/lesson/{lesson}', [CoursesControllerAlias::class, 'lesson'])->name('course.lesson')->middleware('auth');
Route::get('/lesson/{lesson}/finish', [CoursesControllerAlias::class, 'lessonFinish'])->name('course.lesson.finish')->middleware('auth');;
Route::get('/course/curso-diego/module/1/evaluation', function (){
    $eval  = \App\Models\Evaluations::first();
    return view('front.evaluation', compact('eval'));
})->name('course.module.evaluation')->middleware('auth');;


/*
 * Profile section
 */
Route::get('/profile', [UsersControllerAlias::class, 'index'])->name('profile');
Route::post('/profile/{id}/update', [UsersControllerAlias::class, 'update'])->name('profile.update');

/*
 * Payment section
 */
Route::get('/checkout/{course}', [OrdersControllerAlias::class, 'checkout'])->name('order.checkout')->middleware('auth');
Route::get('/checkout/{course}/finish', [OrdersControllerAlias::class, 'finish'])->name('order.checkout.finish');
Route::get('/payment/insert/{course}', [OrdersControllerAlias::class, 'insertPayment'])->name('order.payment.insert');
Route::post('/payment/confirm', [OrdersControllerAlias::class, 'confirmPayment'])->name('order.payment.confirm');
Route::get('/payment/rollback/{order}', [OrdersControllerAlias::class, 'rollbackPayment'])->name('order.payment.rollback');
Route::get('/payment/get/{order}', [OrdersControllerAlias::class, 'getPayment'])->name('order.payment.get');

Route::get('/payment/test', function (){
    $order = \App\Models\Orders::first();
    $course = $order->course;
    return view('front.store.finish', compact('order', 'course'));
})->name('order.payment.get');



Route::get('/miscursos', function(){
    return view('front.profile.miscursos');
});


//Route::middleware(['auth:sanctum', 'verified'])->group()->get('/dashboard', function () {
//    return view('dashboard');
//})->name('dashboard');


Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'middleware' => 'auth:sanctum'
    //'middleware' => ['auth:sanctum', 'role:admin']
], function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('categories', CategoriesController::class);
    Route::resource('courses', CoursesController::class);
    Route::resource('students', StudentsController::class);
    Route::resource('lessons', LessonsController::class);
    Route::resource('comments', CommentsController::class);
    Route::resource('users', UsersController::class);
    Route::resource('orders', OrdersController::class);

    //Route::resource('courses', )
});

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    //Route::resource('categories', CategoriesController::class);
});

app/Http/Controllers/Web/CoursesController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use App\Models\Courses;
use App\Models\Lessons;
use App\Models\UserLessons;
use Illuminate\Http\Request;

class CoursesController extends Controller
{
    public function course($slug)
    {
        if (!$course = Courses::where('slug', '=', $slug)->firstOrFail()) {
            dd('A');
        }

        return view('front.course', compact('course'));
    }

    public function lesson($course, $lesson)
    {
        if (!$lesson = Lessons::where('slug', '=', $lesson)->firstOrFail()) {
            return redirect()->back()->with('error', 'No existe el curso indicado');
        }

        return view('front.lesson', compact('lesson'));
    }


    public function lessonFinish(Lessons $lesson)
    {
        if (!$lesson) {
            return redirect()->back();
        }

        $userlesson = UserLessons::create(['lesson_id' => $lesson->id, 'user_id' => \Auth::id(), 'completed' => true]);

        return redirect()->back();
    }
}

app/Http/Livewire/EditCourse.php
<?php

namespace App\Http\Livewire;

use App\Models\Categories;
use App\Models\CourseCategory;
use App\Models\Courses;
use App\Models\Evaluations;
use App\Models\Items;
use App\Models\LessonFiles;
use App\Models\Lessons;
use App\Models\Modules;
use App\Models\Options;
use Illuminate\Database\Eloquent\Model;
use Livewire\Component;
use Livewire\WithFileUploads;

class EditCourse extends Component
{
    use WithFileUploads;

    public $course;
    public $course_title;
    public $course_resourceNew;
    public $course_intro_resource;
    public $course_description;

    public $modules;

    /* Course Options */
    public $categories;
    public $course_datetime_start;
    public $course_datetime_end;
    public $course_price;

    /* Modules */
    public $moduleSelected;
    public $moduleTitle;

    /* Lesson */
    public $lessonOpen = false;
    public $lesson;
    public $lessonSelected;
    public $lesson_title;
    public $lesson_description;
    public $lesson_resource;
    public $resources = [];
    public $img_resource = [];
    public $confirmDeleteLesson = false;

    /* Evaluation */
    public $evaluationOpen = false;
    public $evalItems = [];
    public $evalOptions = [];
    public $evalItemTitle;
    public $evalItemPoints;
    public $iteration;
    public $evaluationSelected;

    /*
     * Modules section
     */
    public function addModule()
    {
        if (strlen(trim($this->moduleTitle)) == 0) {
            $this->dispatchBrowserEvent('alert', ['type' => 'warning', 'message' => 'El nombre del módulo es requerido']);
            $this->moduleTitle = null;
            return false;
        }

        $sort = Modules::where('course_id', $this->course->id)->orderBy('sort', 'ASC')->get()->last();

        //dd($sort ? $sort->sort + 1 : 1);
        (new Modules())->create([
            'title' => $this->moduleTitle,
            'course_id' => $this->course->id,
            'sort' => ($sort->sort ?? 0) + 1
        ]);

        $this->moduleTitle = null;

        $this->course = Courses::find($this->course->id);
    }

    public function sortModules($sort)
    {
        foreach ($sort as $section) {

            $b = Modules::find($section['value']);
            $b->sort = $section['order'];
            $b->save();
        }

        $this->course = Courses::find($this->course->id);
    }

    public function selectModule(Modules $module)
    {
        $this->moduleSelected = $module;
    }

    public function deleteModule($id)
    {
        Modules::destroy($id);

        $this->course = Courses::find($this->course->id);
    }

    /*
     * Lesson section
     */
    public function addLesson()
    {
        $this->lessonOpen = true;
        $this->unselectLesson();
        $this->dispatchBrowserEvent('GoToElement', 'lesson_form');
    }

    public function createLesson()
    {
        try {
            \DB::beginTransaction();
            $lesson = new Lessons();
            $lesson->title = $this->lesson_title;
            $lesson->description = $this->lesson_description;
            $lesson->module_id = $this->moduleSelected->id;

            $ls = Lessons::where('module_id', $this->moduleSelected->id)->orderByDesc('sort')->first();
            $lesson->sort = $ls ? $ls->sort + 1 : 0 + 1;

            $lesson->save();

            if ($this->lesson_resource) {
                $filename = basename($this->lesson_resource->store('public/courses/' . $this->course->id . '/lessons/' . $lesson->id));
                $lesson->resource_path = 'courses/' . $this->course->id . '/lessons/' . $lesson->id . '/' . $filename;
                $lesson->save();
            }


            if ($this->resources) {
                foreach ($this->resources as $resource) {
                    $resourceFile = new LessonFiles();
                    $filename = basename($resource->store('public/courses/' . $this->course->id . '/lessons/' . $lesson->id . '/resources/'));
                    $resourceFile->filepath = 'courses/' . $this->course->id . '/lessons/' . $lesson->id . '/resources/' . $filename;
                    $resourceFile->filename = $resource->getClientOriginalName();
                    $resourceFile->lesson_id = $lesson->id;
                    $resourceFile->save();
                }
            }

            \DB::commit();

            $this->moduleSelected = Modules::find($this->moduleSelected->id);

            $this->dispatchBrowserEvent('alert', ['type' => 'success', 'message' => 'Lección creada']);
        } catch (\Exception $e) {
            \DB::rollBack();
            \Log::error('livewire/EditCourse@createLesson: ' . $e->getLine() . ' - ' . $e->getMessage());

            $this->dispatchBrowserEvent('alert', ['type' => 'error', 'message' => 'No se pudo crear. Consulte el administrador']);
        }
    }

    public function updateLesson()
    {
        try {
            \DB::beginTransaction();
            $this->lessonSelected->title = $this->lesson_title;
            $this->lessonSelected->description = $this->lesson_description;
            $this->lessonSelected->module_id = $this->moduleSelected->id;
            //$lesson->sort           = Lessons::where('module_id', $this->moduleSelected->id)->orderByDesc('sort')->first()->sort + 1;;
            $this->lessonSelected->save();

            if ($this->lesson_resource) {
                if (\Storage::exists('public/' . $this->lessonSelected->resource_path)) {
                    \Storage::delete('public/' . $this->lessonSelected->resource_path);
                }

                $filename = basename($this->lesson_resource->store('public/courses/' . $this->course->id . '/lessons/' . $this->lessonSelected->id));
                $this->lessonSelected->resource_path = 'courses/' . $this->course->id . '/lessons/' . $this->lessonSelected->id . '/' . $filename;
                $this->lessonSelected->save();

                $this->lesson_resource = null;
            }

            if ($this->resources) {
                foreach ($this->resources as $resource) {
                    $resourceFile = new LessonFiles();
                    $filename = basename($resource->store('public/courses/' . $this->course->id . '/lessons/' . $this->lessonSelected->id . '/resources/'));
                    $resourceFile->filepath = 'courses/' . $this->course->id . '/lessons/' . $this->lessonSelected->id . '/resources/' . $filename;
                    $resourceFile->filename = $resource->getClientOriginalName();
                    $resourceFile->lesson_id = $this->lessonSelected->id;
                    $resourceFile->save();
                }
                $this->resources = null;
            }

            \DB::commit();

            $this->lessonSelected = Lessons::find($this->lessonSelected->id);
            $this->lesson_resource = null;
            $this->resources = null;

            $this->dispatchBrowserEvent('alert', ['type' => 'success', 'message' => 'Lección actualizada']);
        } catch (\Exception $e) {
            \DB::rollBack();
            \Log::error('livewire/EditCourse@updateLesson: ' . $e->getLine() . ' - ' . $e->getMessage());

            $this->dispatchBrowserEvent('alert', ['type' => 'error', 'message' => 'No se pudo actualizar. Consulte el administrador']);
        }
    }

    public function sortLessons($sort)
    {
        foreach ($sort as $lesson) {

            $b = Lessons::find($lesson['value']);
            $b->sort = $lesson['order'];
            $b->save();
        }

        //$this->course = Courses::find($this->course->id);
    }

    public function deleteLessonResource()
    {
        $this->lesson_resource = null;
    }

    public function deleteLessonFiles($id = false, $new = false)
    {

        //dd(\Storage::delete('public/'.$lesson->filepath));
        if ($id) {
            if ($new) {
                unset($this->resources[$id]);
            } else {
                $lesson = LessonFiles::find($id);
                if (\Storage::exists('public/' . $lesson->filepath)) {
                    \Storage::delete('public/' . $lesson->filepath);
                }

                LessonFiles::destroy($id);
            }
        } else {
            unset($this->resources[0]);
        }

        $this->lessonSelected = Lessons::find($this->lessonSelected->id);
    }

    public function selectLesson(Lessons $lesson)
    {
        $this->lessonSelected = $lesson;
        $this->lesson_title = $lesson->title;
        //$this->lesson_resource = $lesson->resource_path;
        //$this->resources = $lesson->files;
        $this->lesson_description = $lesson->description;

        $this->dispatchBrowserEvent('editLesson', $lesson->description);
        //$this->lesson_description = $lesson;
        $this->dispatchBrowserEvent('GoToElement', 'lesson_form');
        $this->lessonOpen = true;
    }

    public function unselectLesson()
    {
        $this->lessonSelected = null;
        $this->lesson_title = null;
        $this->lesson_description = null;
        $this->resources = null;
        $this->lesson_resource = null;
        $this->dispatchBrowserEvent('editLesson', null);
    }

    public function editLesson()
    {
        $this->dispatchBrowserEvent('editLesson');
    }

    public function deleteLesson()
    {
        $lesson = $this->lessonSelected;

        /* Delete lesson files from storage */
        if (\Storage::exists('public/courses/' . $lesson->module->course_id . '/lessons/' . $lesson->id)) {
            \Storage::deleteDirectory('public/courses/' . $lesson->module->course_id . '/lessons/' . $lesson->id);
        }
        $lesson->delete();

        $this->confirmDeleteLesson = false;
        $this->unselectLesson();
        $this->moduleSelected = Modules::find($this->moduleSelected->id);

        $this->dispatchBrowserEvent('alert', ['type' => 'success', 'message' => 'Curso eliminado']);
    }

    /*
     * Evaluation section
     */
    public function addEvaluation()
    {

resources/views/administration/courses/edit.blade.php
@extends('administration.layout.app')
@section('styles')

    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    @livewireStyles
    <style>
        input[type=file] {
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
            width: 150px;
        }
    </style>
@endsection
@section('content')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                Cursos
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Admin</a></li>
                    <li class="breadcrumb-item" aria-current="page">Cursos</li>
                    <li class="breadcrumb-item active" aria-current="page">Editar</li>
                </ol>
            </nav>
        </div>
        @livewire('edit-course', ['course' => $course, 'categories' => $categories])
    </div>
@endsection
@section('scripts')
    <script src="\administration\js\select2.js"></script>
    <script src="https://cdn.tiny.cloud/1/le0xnl72caevg2xl8a4noobxfd3cuv10352omp6pa0ieawfi/tinymce/5/tinymce.min.js"
            referrerpolicy="origin"></script>
    <script>
        $(document).ready(function () {


            window.addEventListener('editLesson',function(e){
                tinymce.get('lesson_description').setContent(e.detail);

            })
        })

    </script>
    <script type="text/javascript">
        // Upload Images
        $('.products_uploader').change(function () {
            var imageContainer = $('#preview_images');
            imageContainer.empty();
            console.log('Upload Images');
            var quantity = this.files.length;
            console.log('Quantity: ' + quantity);
            var anyWindow = window.URL || window.webkitURL;
            for (var i = 0; i < quantity; i++) {
                console.log('Create a new image for index ' + i);
                var objectUrl = anyWindow.createObjectURL(this.files[i]);
                imageContainer.append('<div class="col-md-2 product_image" id="image_' + i + '" data-id="' + i + '">' +
                    '<img class="image_preview" style="width: 150px; height: 150px" src="' + objectUrl + '" />' +
                    '</div>');
                window.URL.revokeObjectURL(this.files[i]);
            }
        });
        // Select main image
        $(document).on('click', 'img.image_preview', function (e) {
            $('#preview_images .product_image img').removeClass('selected');
            var data_id = $(this).parent().data('id');
            console.log('New main image: ' + data_id);
            $(this).addClass('selected');
            $('#main_image').val(data_id);
        });
    </script>
    @livewireScripts
    @stack('livewire_scripts')
    <script>
        window.addEventListener('alert',function(e){

            //Notifications from Livewire
            switch (e.detail['type']) {
                case 'success':
                    showSuccessToast(e.detail.message)

                    break;

                case 'error':
                    showDangerToast(e.detail.message)
                    break;

                case 'info':
                    showInfoToast(e.detail.message)
                    break;

                case 'warning':
                    showWarningToast(e.detail.message)
                    break;
            }
            //END Notifications from Livewire
        })

        window.addEventListener('GoToElement',function(e){
            $("html, body").animate({ scrollTop: $('#'+e.detail).offset().top }, 500);
        })

    </script>
    <script src="/administration/js/livewire-sortable.js"></script>
    {{--<script src="/administration/js/dragula.js"></script>--}}
@endsection

resources/views/administration/courses/form.blade.php
@extends('administration.layout.app')
@section('styles')

    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
@endsection
@section('content')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                Cursos
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Admin</a></li>
                    <li class="breadcrumb-item" aria-current="page">Cursos</li>
                    <li class="breadcrumb-item active" aria-current="page">Crear</li>
                </ol>
            </nav>
        </div>
        <div class="row">
            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        {{--@if($errors->first())
                            @dd($errors)
                        @endif--}}
                        @isset ($course)
                            <h4 class="card-title">Editar curso</h4>
                        @else
                            <h4 class="card-title">Crear curso</h4>
                        @endisset
                        <p class="card-description">
                            Carga la información del curso
                        </p>
                        @isset ($course)
                            {!! Form::model($course, ['route' => ['admin.courses.update', $course->id], 'method' => 'PATCH','files' => true]) !!}
                        @else
                            {!! Form::open(['route' => 'admin.courses.store', 'method' => 'post' ,'files' => true]) !!}
                        @endisset

                        <div class="form-group row">
                            <div class="col-sm-5">
                                <label>Título (requerido *):</label>
                                {!! Form::text('title', old('title'), ['class' => 'form-control form-control-sm'.($errors->has('title') ? ' is-invalid': '')]) !!}
                                @error('title')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <div class="col-sm-3">
                                <label>Categorías (requerido *):</label>
                                {!! Form::select('categories[]', $categories , isset($course) ? $course->categories->pluck('id') : old('categories'), ['class' => 'js-example-basic-multiple form-control'.($errors->has('categories') ? ' is-invalid': ''), 'multiple', 'style' => 'width:100%']) !!}
                                @error('categories')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <div class="col-sm-2">
                                <label>Fecha/Hora Inicio (opcional):</label>
                                {{ Form::input('dateTime-local', 'datetime_start', isset($course) ? strftime('%Y-%m-%dT%H:%M', strtotime($course->datetime_start)) : old('datetime_start'), ['class' => 'form-control form-control-sm'.($errors->has('datetime_start') ? ' is-invalid': '')]) }}
                                @error('datetime_start')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <div class="col-sm-2">
                                <label>Fecha/Hora Fin (opcional):</label>
                                {{ Form::input('dateTime-local', 'datetime_end', isset($course) ? strftime('%Y-%m-%dT%H:%M', strtotime($course->datetime_end)) : old('datetime_end'), ['class' => 'form-control form-control-sm'.($errors->has('datetime_end') ? ' is-invalid': '')]) }}
                                @error('datetime_end')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-3">
                                <label>Precio (requerido *):</label>
                                {!! Form::number('price', null, ['class' => 'form-control form-control-sm'.($errors->has('price') ? ' is-invalid': '')]) !!}
                                @error('price')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <div class="col-sm-5">
                                <label>Imagen:</label>
                                <div class="col-sm-12">
                                    <input type="file" name="intro_resource" class="form-control form-control-sm @error('intro_resource') is-invalid @enderror"
                                           accept="image/*,video/*">
                                    @error('intro_resource')
                                    <div class="invalid-feedback">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label for="exampleTextarea1">Descripción (requerido *)</label>
                                    {!! Form::textarea('description', old('description') ?? isset($course) ? $course->description : '', ['rows' => '3','class' => 'form-control'.($errors->has('description') ? ' is-invalid': ''), 'id' => 'tinyEditor']) !!}
                                    @error('description')
                                    <div class="invalid-feedback">
                                        {{ $message }}
                                    </div>
                                    @enderror
                                    {{--<textarea name="content_text" id="summernote"></textarea>--}}
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary mr-2">Guardar</button>
                        <a href="{{ route('admin.categories.index') }}" class="btn btn-light">Cancelar</a>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script src="\administration\js\select2.js"></script>
    <script src="https://cdn.tiny.cloud/1/le0xnl72caevg2xl8a4noobxfd3cuv10352omp6pa0ieawfi/tinymce/5/tinymce.min.js"
            referrerpolicy="origin"></script>
    <script>
        tinymce.init({
            menubar: false,
            height: 350,
            selector: 'textarea',
            plugins: [
                'advlist autolink lists link image charmap print preview anchor',
                'searchreplace visualblocks code fullscreen',
                'insertdatetime media table paste code help wordcount'
            ],
            toolbar: 'undo redo | bold italic underline strikethrough ' +
                '| fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | ' +
                'outdent indent |  numlist bullist | forecolor backcolor removeformat | emoticons | fullscreen  preview',
        });
    </script>
    <script type="text/javascript">
        // Upload Images
        $('.products_uploader').change(function () {
            var imageContainer = $('#preview_images');
            imageContainer.empty();
            console.log('Upload Images');
            var quantity = this.files.length;
            console.log('Quantity: ' + quantity);
            var anyWindow = window.URL || window.webkitURL;
            for (var i = 0; i < quantity; i++) {
                console.log('Create a new image for index ' + i);
                var objectUrl = anyWindow.createObjectURL(this.files[i]);
                imageContainer.append('<div class="col-md-2 product_image" id="image_' + i + '" data-id="' + i + '">' +
                    '<img class="image_preview" style="width: 150px; height: 150px" src="' + objectUrl + '" />' +
                    '</div>');
                window.URL.revokeObjectURL(this.files[i]);
            }
        });
        // Select main image
        $(document).on('click', 'img.image_preview', function (e) {
            $('#preview_images .product_image img').removeClass('selected');
            var data_id = $(this).parent().data('id');
            console.log('New main image: ' + data_id);
            $(this).addClass('selected');
            $('#main_image').val(data_id);
        });
    </script>
@endsection

resources/views/administration/courses/index.blade.php
@extends('administration.layout.app')
@section('content')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                Cursos
            </h3>
        </div>
        <div class="row">
            <div class="col-md-8 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">
                            <i class="fas fa-newspaper"></i>
                            Cursos
                            <a href="{{ route('admin.courses.create') }}" class="fa-pull-right btn btn-info btn-xs"><i
                                    class="fas fa-plus"></i></a>
                        </h4>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Curso</th>
                                    <th>Acciones</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($courses as $course)
                                    <tr>
                                        <td class="font-weight-bold">
                                            {{ $course->id }}
                                        </td>
                                        <td class="text-muted">
                                            {{ $course->title }}
                                        </td>
                                        <td>
                                            {!! Form::open(['route' => ['admin.courses.destroy', $course->id], 'method' => 'DELETE']) !!}
                                            <button type="submit" class="btn btn-outline-danger btn-xs"><i
                                                    class="fas fa-trash"></i></button>
                                            {!! Form::close() !!}
                                            <a href="{{ route('admin.courses.edit', $course->id) }}"
                                               class="btn btn-outline-info btn-xs"><i class="fas fa-pencil-alt"></i></a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection